# Generated by Django 3.2.7 on 2021-09-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_auto_20210915_2142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
    ]
