# Generated by Django 3.2.7 on 2021-09-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0003_rename_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='昵称', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('register_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(error_messages={'unique': 'A code with that course already exists.'}, help_text='课程代码', max_length=10),
        ),
    ]
